## AIM 5001 Week 4 Assignment (NumPy)

### Alejandra Zapata

## Task 1

In [18]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

result=np.intersect1d(a,b) #intersect is the distinct common values between both a & b
print(result)

[2 4]


## Task 2

In [19]:
c=np.arange(1,16).reshape(3,5) #np.arange creates an array with consecutive numbers from 1-16 and shapes a 2D array
c.T #switches the elements of rows to the columns

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## Task 3

In [20]:
x = np.array([12, 5, 7, 15, 3, 1, 8])
y = np.array([14, 6, 3, 11, 19, 12, 5])

xy=np.intersect1d(x,y) #creates a new array with the common values

np.setdiff1d(x,xy) #drops the common values

array([ 1,  7,  8, 15])

## Task 4

In [23]:
1437/31

46.354838709677416

In [21]:
#There is 1437 mi netween NYC and Key West Florida
#We add 31 elements because that is the number of days we biked
a=np.zeros(31) #an array where all the values equal 0 and has 31 elements

#Instead of using the np.random function we avoid getting very different
# values for each elemet (Ex. Day 1 could be 1000 miles)
#We use 47 for all the elements as an approximation of biking the same distance everyday
a[0:31]=47 

a[30]=27 #this appends the last element to be 27 to have a total sum of 1437
print(a)
print ('The sum of this array is',(np.sum(a)))

[47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47.
 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 47. 27.]
The sum of this array is 1437.0


In [22]:
np.cumsum(a) 
#np.cumsum gives us an array that adds the previous values until the end of the array which equals 
#the number of miles between NYC and Key West

array([  47.,   94.,  141.,  188.,  235.,  282.,  329.,  376.,  423.,
        470.,  517.,  564.,  611.,  658.,  705.,  752.,  799.,  846.,
        893.,  940.,  987., 1034., 1081., 1128., 1175., 1222., 1269.,
       1316., 1363., 1410., 1437.])

## Task 5

In [2]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [4]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

In [6]:
new=nyc_water.T #by transposing the data we can treat each column as an index

In [13]:
np.amax(new[2]) #maximum yearly NYC consumption in millions per gallon

1512.0

In [14]:
np.shape(new[0])#count of years on the table

(39,)

In [15]:
np.mean(new[3]) #the mean of per capita daily water consumption

160.30769230769232

In [16]:
np.std(new[3]) #the standard deviation of per capita daily water consumption

31.51894330370624

In [17]:
pop_diff=np.diff(new[1]) #the increase or decrease on population
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])